### ISSUE TITLE
[Todo] GCS 이미지 관리 API

### ISSUE THREAD

**Issue by Feedbaek** [CUK-CRUSH/Duett-Server#7]
## GCS 이미지 관리 API
- [x] GCS 관련 설정
- [x] GCS 이미지 API 만들기
- [x] 테스트 코드 작성
